services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.0.8-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: iamfly
      RABBITMQ_DEFAULT_PASS: iamfly
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - pastebin

  ms_redis_hash:
    container_name: ms_redis_hash
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - pastebin


  ms_redis_urls:
    container_name: ms_redis_urls
    image: redis:latest
    restart: always
    ports:
      - "6380:6379"
    networks:
      - pastebin



  ms_postgres_urlref:
    container_name: ms_postgres_urlref
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: iamfly
      POSTGRES_PASSWORD: iamfly
      POSTGRES_DB: urlrefs_db
    networks:
      - pastebin

  ms_postgres_hash:
    container_name: ms_postgres_hash
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: iamfly
      POSTGRES_PASSWORD: iamfly
      POSTGRES_DB: hashid_db
    networks:
      - pastebin


  api-service:
    container_name: api-service
    image: api-service:latest
    ports:
      - "8000:8000"
    networks:
      - pastebin
    depends_on:
      - rabbitmq


  hash-generator:
    container_name: hash-generator
    image: hash-generator:latest
    ports:
      - "8001:8001"
    networks:
      - pastebin
    depends_on:
      - api-service

networks:
  pastebin:
    driver: bridge
