spring:
  main:
    allow-circular-references: true
  application:
    name: hash-generator
  rabbitmq:
    host: rabbitmq
    password: iamfly
    username: iamfly
    port: 5672
  r2dbc:
    url: r2dbc:postgresql://ms_postgres_hash:5432/hashid_db
    username: iamfly
    password: iamfly

    pool:
      enabled: true
      max-size: 20
      initial-size: 5
      max-idle-time: 30m
      max-life-time: 10m
  data:
    redis:
      host: ms_redis_hash
      port: 6379

server:
  port: 8001